### ISSUE TITLE
Deno example

### ISSUE THREAD

**Issue by ddorstijn** [eclipsesource/pdf-maker#30]
In the description you say it is possible to use the function in deno. Could you give us an example as of how this would be possible? Do you mean by using the compatability layer of deno?

**Comment by ralfstx** [comment]
I'm sorry, I've missed this issue. There is now a README in the [examples](https://github.com/eclipsesource/pdf-maker/tree/main/examples) folder that explains how to run the examples with Deno. Meanwhile, they run out of the box.
