### ISSUE TITLE
Unsupported width attribute 'auto' in examples/sample.js

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/pdf-maker#58]
The example defines a header column of width `auto` here:
https://github.com/eclipsesource/pdf-maker/blob/671db0ecd7b3f5ddc053e16422c04fb52ba2afae/examples/sample.js#L36

that apparently isn't a supported length unit and causes this error:
```
error: Uncaught Error: Supplied function returned invalid value: Invalid value for "columns/1/width": Expected number or length string, got: 'auto'
```

BTW, the _About_ text on the project's GitHub home page reads:
> Generate PDF documents and from a JSON definition

The word 'and' seems to be inserted by accident.

**Comment by ralfstx** [comment]
Which version of `pdfmkr` did you use? The example works for me with `npm install pdfmkr@^0.4.2`.

Thanks about the notice on the *About* text. Fixed.

**Comment by rherrmann** [comment]
> Which version of `pdfmkr` did you use? The example works for me with `npm install pdfmkr@^0.5.2`.

I've been using 0.5.1 with Deno, after upgrading to 0.5.2 the issue is gone.
